services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  ttimbers/dsci522-dockerfile-practice-tt:eaed841
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
